web:
  cors:
    allowed-origins: "*"
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    allowed-headers: "*"
    exposed-headers: "*"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/asset_mgt
    username: postgres
    password: 1!kirtan
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hbm2ddl:
        auto: update
jwt:
  secret-key: |
    afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf
